name: Build minimal OpenWrt for WNDR4300

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出仓库
      - uses: actions/checkout@v3

      # 第二步：下载并解压 ImageBuilder
      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/19.07.9/targets/ath79/generic/openwrt-imagebuilder-19.07.9-ath79-generic.Linux-x86_64.tar.xz
          tar -xJf openwrt-imagebuilder-*.tar.xz

      # 第三步：编译固件（只包含 kmod-tun 和 tailscale）
      - name: Build firmware
        run: |
          cd openwrt-imagebuilder-19.07.9-ath79-generic.Linux-x86_64
          make image PROFILE=WNDR4300 PACKAGES="kmod-tun tailscale"

      # 第四步：上传产物到 GitHub Artifacts
      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: factory-bin
          path: bin/targets/ath79/generic/*.factory.bin
